#include "src/Utility.h"
#include "src/ActorListGenerator.hpp"
#include "src/CMakeGenerator.hpp"
#include "src/FileGenerator.hpp"
#include "src/SourceGenerator.hpp"
#include "src/ReleaseBuild.hpp"

void getConfig(YAML::Node& config, std::string& name)
{
    try
    {
        std::string tmp = UBT::getPath() + "uvproj.yaml";
        config = YAML::LoadFile(tmp);
    }
    catch (YAML::BadFile&)
    {
        std::cout << "Could not locate file" << std::endl;
        std::terminate();
    }

    if (config["name"])
    {
        name = config["name"].as<std::string>();
    }
}

int main(int argc, char** argv)
{
    UBT::setPath("../../");
    if (argc < 2)
    {
        std::cout << "Not enough arguments passed into the generator!" << std::endl;
        return 0;
    }
    if (argv[1] == UBT::toLower("--help"))
    {
        std::cout << "UVKBuildTool - The universal Untitled Vulkan Game Engine file generator" << std::endl;
        std::cout << "  --generate <project path> - generate autogenerated files for your project" << std::endl;
	    std::cout << "  --install <project path> - generates first time install project files" << std::endl;
        std::cout << "  --help - this help message" << std::endl;
        std::cout << "  --build <project path> - build creates a release build for the application" << std::endl;
        std::cout << "Commands bellow this line, generate project files, with the first argument specifying the type and the second the name!" << std::endl;
        std::cout << "  --scriptable-object <name> <add or remove> <project path>" << std::endl;
        std::cout << "  --pawn <name> <project path>" << std::endl;
        std::cout << "  --game-mode <name> <project path>" << std::endl;
        std::cout << "  --game-state <name> <project path>" << std::endl;
        std::cout << "  --player-state <name> <project path>" << std::endl;
        std::cout << "  --player-controller <name> <project path>" << std::endl;
        std::cout << "  --level <name> <project path>" << std::endl;
        std::cout << "UVKBuild tool, made by MadLad Squad, developed and maintained by Stanislav Vasilev(Madman10K)" << std::endl;
        return 0;
    }

    YAML::Node config;
    std::string name;
    if (argv[1] == UBT::toLower("--generate") && argc < 4)
    {
        UBT::setPath(argv[2]);
        getConfig(config, name);
        bool bSetReadable;

        std::string startupLevelName;

        std::ifstream i(UBT::getPath() + "Generated/ActorList.hpp");
        bSetReadable = i.is_open();

        if (config["startup-level"])
        {
            startupLevelName = config["startup-level"].as<std::string>();
        }

        UBT::CMakeInfoData data;

        UBT::addIncludeDirectories(config, data);
        UBT::addSubdirectories(config, data);
        UBT::addLinkLibraries(config, data);
        UBT::addHeaderLibraries(config, data);
        UBT::addSourceLibraries(config, data);

        if (!bSetReadable) UBT::generateSet();
        UBT::generateCmake(name.c_str(), data);
        UBT::generateGame(name.c_str());
        UBT::generateMain(startupLevelName.c_str(), name.c_str());
        UBT::generateDef();

        return 0;
    }
    else if (argv[1] == UBT::toLower("--install") && argc < 4)
    {
        UBT::setPath(argv[2]);
        getConfig(config, name);
        bool bSetReadable;
        std::string startupLevelName;

        std::ifstream i(UBT::getPath() + "Generated/ActorList.hpp");
        bSetReadable = i.is_open();

        if (config["startup-level"])
        {
            startupLevelName = config["startup-level"].as<std::string>();
        }

        if (config["name"])
        {
            name = config["name"].as<std::string>();
        }

        UBT::CMakeInfoData data;

        UBT::addIncludeDirectories(config, data);
        UBT::addSubdirectories(config, data);
        UBT::addLinkLibraries(config, data);
        UBT::addHeaderLibraries(config, data);
        UBT::addSourceLibraries(config, data);

        if (!bSetReadable) UBT::generateSet();
        UBT::generateCmake(name.c_str(), data);
        UBT::generateGame(name.c_str());
        UBT::generateMain(startupLevelName.c_str(), name.c_str());
        UBT::generateDef();
        UBT::generateWrapperAndMod();
        UBT::makeTemplate("StartupLevel", "UVK::Level", name.c_str());
		UBT::makeTemplate(static_cast<std::string>(name + std::string("GameInstance")), "UVK::GameInstance", name.c_str());

		return 0;
    }
    else if (argv[1] == UBT::toLower("--build"))
    {
        UBT::setPath(argv[2]);
        getConfig(config, name);
        UBT::relBuild(config["name"].as<std::string>());
        return 0;
    }

    if (argc < 4)
    {
        std::cout << "Not enough arguments passed into the generator!" << std::endl;
        return 0;
    }
    else if (argc == 4)
    {
        UBT::setPath(argv[3]);
        getConfig(config, name);
        if (argv[1] == UBT::toLower("--pawn"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::Pawn", name.c_str());
            return 0;
        }
        else if (argv[1] == UBT::toLower("--game-mode"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::GameMode", name.c_str());
            return 0;
        }
        else if (argv[1] == UBT::toLower("--game-state"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::GameState", name.c_str());
            return 0;
        }
        else if (argv[1] == UBT::toLower("--player-state"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::PlayerState", name.c_str());
            return 0;
        }
        else if (argv[1] == UBT::toLower("--player-controller"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::PlayerController", name.c_str());
            return 0;
        }
        else if (argv[1] == UBT::toLower("--level"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::Level", name.c_str());
            return 0;
        }
    }

    if (argc < 5)
    {
        std::cout << "Not enough arguments passed into the generator!" << std::endl;
        return 0;
    }
    else if (argc == 5)
    {
        UBT::setPath(argv[4]);
        getConfig(config, name);
        if (argv[1] == UBT::toLower("--scriptable-object") && argv[3] == UBT::toLower("--add"))
        {
            UBT::makeTemplate(std::string(argv[2]), "UVK::ScriptableObject", name.c_str());
            UBT::addClass("Source/" + std::string(argv[2]) + ".hpp");
            return 0;
        }
        else if (argv[1] == UBT::toLower("--scriptable-object") && argv[3] == UBT::toLower("--remove"))
        {
            UBT::removeClass("Source/" + std::string(argv[2]) + ".hpp");
            return 0;
        }

    }
}
